In [19]:
from CHAID import Tree
import numpy as np
import pandas as pd

In [20]:
from CHAID import Tree

ndarr = np.array(([1.7, 2.5, 3.1] * 5) + ([2, 2, 3] * 5)).reshape(10, 3)
df = pd.DataFrame(ndarr)
df.columns = ['a', 'b', 'c']
arr = np.array(([1] * 5) + ([2] * 5))
df['d'] = arr
df

a    b    c  d
0  1.7  2.5  3.1  1
1  1.7  2.5  3.1  1
2  1.7  2.5  3.1  1
3  1.7  2.5  3.1  1
4  1.7  2.5  3.1  1
5  2.0  2.0  3.0  2
6  2.0  2.0  3.0  2
7  2.0  2.0  3.0  2
8  2.0  2.0  3.0  2
9  2.0  2.0  3.0  2

In [21]:
## set the CHAID input parameters
independent_variable_columns = ['a', 'b', 'c']
dep_variable = 'd'

In [22]:
dict(zip(independent_variable_columns,'categorical'*3))

{'a': 'c', 'b': 'a', 'c': 't'}

In [23]:
arr

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2])

In [24]:
ndarr

array([[ 1.7,  2.5,  3.1],
       [ 1.7,  2.5,  3.1],
       [ 1.7,  2.5,  3.1],
       [ 1.7,  2.5,  3.1],
       [ 1.7,  2.5,  3.1],
       [ 2. ,  2. ,  3. ],
       [ 2. ,  2. ,  3. ],
       [ 2. ,  2. ,  3. ],
       [ 2. ,  2. ,  3. ],
       [ 2. ,  2. ,  3. ]])

In [25]:
## create the same tree, but without pandas helper
tree = Tree(ndarr, arr, split_titles=['a', 'b', 'c'], min_child_node_size=5)

In [26]:
tree.print_tree()

([], {1: 5, 2: 5}, (a, p=0.001565402258002549, score=10.0, groups=[[1.7], [2.0]]), dof=1))
├── ([1.7], {1: 5, 2: 0}, <Invalid Chaid Split> - the minimum parent node size threshold has been reached)
└── ([2.0], {1: 0, 2: 5}, <Invalid Chaid Split> - the minimum parent node size threshold has been reached)



In [28]:
tree.tree_store[0].split.column

'a'

In [11]:
# un nuevo dataset
iris = pd.read_csv('DataSets/Iris.csv')

In [12]:
a = iris[['SepalLength','SepalWidth','PetalLength','PetalWidth']]
a.as_matrix()

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [13]:
b = iris['Species']
b.as_matrix()

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
tree = Tree(a.as_matrix(),b.as_matrix(),split_titles=['SepalLength','SepalWidth','PetalLength','PetalWidth'],min_child_node_size=5)

In [15]:
tree.print_tree()

([], {0: 50, 1: 50}, (SepalLength, p=6.114629521409371e-15, score=60.86434573829532, groups=[[4.2999999999999998, 4.4000000000000004, 4.5, 4.5999999999999996, 4.7000000000000002, 4.7999999999999998, 4.9000000000000004, 5.0, 5.4000000000000004, 5.2000000000000002, 5.0999999999999996, 5.2999999999999998], [5.5, 5.7000000000000002, 5.7999999999999998, 6.5, 6.7999999999999998, 6.9000000000000004, 7.0, 5.9000000000000004, 6.2000000000000002, 6.4000000000000004, 6.5999999999999996, 6.2999999999999998, 6.7000000000000002, 6.0, 6.0999999999999996, 5.5999999999999996]]), dof=1))
├── ([4.2999999999999998, 4.4000000000000004, 4.5, 4.5999999999999996, 4.7000000000000002, 4.7999999999999998, 4.9000000000000004, 5.0, 5.4000000000000004, 5.2000000000000002, 5.0999999999999996, 5.2999999999999998], {0: 6, 1: 45}, (SepalWidth, p=6.934965200849098e-09, score=33.55296296296296, groups=[[2.0, 2.2999999999999998, 2.3999999999999999, 2.5, 2.7000000000000002], [2.8999999999999999, 3.0, 4.0999999999999996, 3.

In [18]:
#Las primeras dos variables que influyen en la variable objetivo
print(tree.tree_store[0].split.column)
print(tree.tree_store[1].split.column)

SepalLength
SepalWidth
